language: php
php:
  - "5.5"
  - "5.6"
  - "7.0"
  - hhvm
sudo: false
env:
addons:
  apt:
    packages:
      - nodejs
before_script:
  - composer install
  # - php artisan key:generate
script:
  - phpunit --exclude-group testDotEnvVars
