version: '3.9'

# For development purposes only, as easy passwords are hardcoded

services:
  #PHP Service
  app:
    image: irail-v2
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      APP_NAME: irail-api
      APP_ENV: local
      APP_KEY:
      APP_DEBUG: 'true'
      APP_URL: 'http://localhost'
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: 'irail-api'
      DB_USERNAME: 'irail-api'
      DB_PASSWORD: 'irail-api'
    extra_hosts:
      - host.docker.internal:host-gateway
    working_dir: /var/www
    networks:
      - app
    volumes:
      - ./:/var/www
      - ./docker/debug:/tmp/xdebug
    links:
      - db
    ports:
      - "8088:8080"
  #MySQL Service
  db:
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: irail-api
      POSTGRES_USER: irail-api
      POSTGRES_PASSWORD: irail-api
      POSTGRES_ROOT_PASSWORD: irail-api
      TZ: Europe/Stockholm
    ports:
      - "54320:5432"
    networks:
      - app
    volumes:
      - irailv2_sqldata:/var/lib/postgresql/data
  web:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/
      - ./deployment/nginx.docker.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    networks:
      - app

#Docker Networks
networks:
  app:
    driver: bridge

#Docker internal volumes
volumes:
  irailv2_sqldata:
    name: "irailv2_sqldata"