
GET https://mobile-riv.api.belgianrail.be/riv/v1.0/journey?trainFilter=S206466&originExtId=008821006&destExtId=008821105&date=2022-11-06&time=19%3A01%3A00&lang=EN
x-api-key: IOS-v0001-20190214-YKNDlEPxDqynCovC2ciUOYl8L6aMwU4WuhKaNtxl
User-Agent: BelgianTrain/11 CFNetwork/1335.0.3 Darwin/21.6.0



GET https://mobile-riv.api.belgianrail.be/riv/v1.0/journey?trainFilter=S206466&originExtId=008821006&destExtId=008821105&date=2022-11-06&time=19%3A01%3A00&lang=EN
x-api-key: IOS-v0001-20190214-YKNDlEPxDqynCovC2ciUOYl8L6aMwU4WuhKaNtxl
User-Agent: BelgianTrain/11 CFNetwork/1335.0.3 Darwin/21.6.0