<?php

namespace Irail\Http\Requests;

use Illuminate\Http\Request;
use Illuminate\Support\Str;

class RequestUuidHelper
{
    /**
     * Get the UUID for a request. Once created, the UUID is stored in the X-Request-Id header so it can be obtained again later.
     * @param Request $request The request for which to obtain a UUID
     * @return string
     */
    public static function getRequestId(Request $request): string
    {
        // The server object cannot be set by the client, this id is always generated by iRail
        $currentValue = $request->server->get('X-Request-Id', null);
        if ($currentValue) {
            return $currentValue;
        }
        $newId = self::createUuid();
        $request->server->set('X-Request-Id', $newId);
        return $newId;
    }

    /**
     * @return string
     */
    private static function createUuid(): string
    {
        return (string)Str::orderedUuid();
    }
}