<?php
/*
    Copyright 2008, 2009, 2010 Yeri "Tuinslak" Tiete (http://yeri.be), and others
    Copyright 2010 Pieter Colpaert (pieter@irail.be - http://bonsansnom.wordpress.com)

	This file is part of iRail.

    iRail is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    iRail is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with iRail.  If not, see <http://www.gnu.org/licenses/>.

	http://project.irail.be - http://irail.be

	source available at http://github.com/Tuinslak/iRail
*/

$stations = array(  'AALST',
        'AALST KERREBROEK',
        'AALTER',
        'AARSCHOT',
        'AARSELE',
        'ACREN',
        'AISEAU',
        'ALKEN',
        'AMAY',
        'AMPSIN',
        'ANDENNE',
        'ANGLEUR',
        'ANS',
        'ANSEREMME',
        'ANTOING',
        'ANTWERPEN BERCHEM',
        'ANTWERPEN CENTRAAL',
        'ANTWERPEN DAM',
        'ANTWERPEN NOORDERDOKKEN',
        'ANTWERPEN OOST',
        'ANTWERPEN ZUID',
        'ANZEGEM',
        'APPELTERRE',
        'ARCHENNES',
        'ARLON',
        'ASSE',
        'ASSESSE',
        'ATH',
        'AUVELAIS',
        'AYE',
        'AYWAILLE',
        'BAASRODE ZUID',
        'BALEGEM DORP',
        'BALEGEM ZUID',
        'BALEN',
        'BAMBRUGGE',
        'BARVAUX',
        'BAS OHA',
        'BASSE WAVRE',
        'BASTOGNE NORD',
        'BASTOGNE SUD',
        'BEAURAING',
        'BEERNEM',
        'BEERSEL',
        'BEGIJNENDIJK',
        'BEIGNEE',
        'BELLEM',
        'BELSELE',
        'BERCHEM SAINTE AGATHE',
        'BERINGEN',
        'BERLAAR',
        'BERTRIX',
        'BERZEE',
        'BEUZET',
        'BEVEREN',
        'BIERGES WALIBI',
        'BIERSET AWANS',
        'BILZEN',
        'BINCHE',
        'BISSEGEM',
        'BLANKENBERGE',
        'BLANMONT',
        'BLATON',
        'BLERET',
        'BOCKSTAEL',
        'BOECHOUT',
        'BOITSFORT',
        'BOKRIJK',
        'BOMAL',
        'BOOISCHOT',
        'BOOM',
        'BOONDAAL',
        'BOORTMEERBEEK',
        'BORDET',
        'BORGWORM',
        'BORNEM',
        'BOSVOORDE',
        'BOUSSU',
        'BOUWEL',
        'BRACQUEGNIES',
        'BRAINE L ALLEUD',
        'BRAINE LE COMTE',
        'BRESSOUX',
        'BRUGELETTE',
        'BRUGGE',
        'BRUGGE ST PIETERS',
        'BRUSSEL CENTRAAL',
        'BRUSSEL CONGRES',
        'BRUSSEL KAPELLEKERK',
        'BRUSSEL LUXEMBURG',
        'BRUSSEL NAT LUCHTHAVEN',
        'BRUSSEL NOORD',
        'BRUSSEL SCHUMAN',
        'BRUSSEL ZUID',
        'BRUXELLES CENTRAL',
        'BRUXELLES CHAPELLE',
        'BRUXELLES CONGRES',
        'BRUXELLES MIDI',
        'BRUXELLES NAT AEROPORT',
        'BRUXELLES NORD',
        'BRUXELLES LUXEMBOURG',
        'BRUXELLES SCHUMAN',
        'BUDA',
        'BUGGENHOUT',
        'BUIZINGEN',
        'BURST',
        'CALLENELLE',
        'CAMBRON CASTEAU',
        'CARLSBOURG',
        'CARNIERES',
        'CEROUX MOUSTY',
        'CHAPELLE DIEU',
        'CHAPOIS',
        'CHARLEROI OUEST',
        'CHARLEROI SUD',
        'CHASTRE',
        'CHATEAU DE SEILLES',
        'CHATELET',
        'CHENEE',
        'CINEY',
        'COMBLAIN LA TOUR',
        'COMINES',
        'COO',
        'COUILLET',
        'COUR SUR HEURE',
        'COURCELLES MOTTE',
        'COURRIERE',
        'COURT SAINT ETIENNE',
        'COUVIN',
        'DAVE SAINT MARTIN',
        'DE HOEK',
        'DE PANNE',
        'DE PINTE',
        'DEINZE',
        'DELTA',
        'DENDERLEEUW',
        'DENDERMONDE',
        'DIEGEM',
        'DIEPENBEEK',
        'DIEST',
        'DIKSMUIDE',
        'DILBEEK',
        'DINANT',
        'DOLHAIN GILEPPE',
        'DOORNIK',
        'DRONGEN',
        'DUFFEL',
        'DUINBERGEN',
        'ECAUSSINNES',
        'EDE',
        'EDINGEN',
        'EEKLO',
        'EICHEM',
        'EIGENBRAKEL',
        'EINE',
        'EKE NAZARETH',
        'EKEREN',
        'ENGHIEN',
        'ENGIS',
        'EPPEGEM',
        'ERBISOEUL',
        'EREMBODEGEM',
        'ERNAGE',
        'ERPE MERE',
        'ERPS KWERPS',
        'ERQUELINNES',
        'ERQUELINNES VILLAGE',
        'ESNEUX',
        'ESSEN',
        'ESSENE LOMBEEK',
        'ETTERBEEK',
        'EUPEN',
        'EVERE',
        'EZEMAAL',
        'FAMILLEUREUX',
        'FARCIENNES',
        'FAUX',
        'FEXHE LE HAUT CLOCHER',
        'FLAWINNE',
        'FLEMALLE GRANDE',
        'FLEMALLE HAUTE',
        'FLEURUS',
        'FLOREE',
        'FLOREFFE',
        'FLORENVILLE',
        'FLORIVAL',
        'FONTAINE VALMONT',
        'FORCHIES',
        'FOREST EST',
        'FOREST MIDI',
        'FORRIERES',
        'FRAIPONT',
        'FRAMERIES',
        'FRANCHIMONT',
        'FRANIERE',
        'FROYENNES',
        'GALMAARDEN',
        'GASTUCHE',
        'GAVERE ASPER',
        'GEDINNE',
        'GEEL',
        'GEMBLOUX',
        'GENDRON CELLES',
        'GENK',
        'GENLY',
        'GENT DAMPOORT',
        'GENT SINT PIETERS',
        'GENTBRUGGE',
        'GENVAL',
        'GERAARDSBERGEN',
        'GHLIN',
        'GLONS',
        'GODARVILLE',
        'GODINNE',
        'GONTRODE',
        'GOUVY',
        'GOUY LEZ PIETON',
        'GRAIDE',
        'GROENENDAAL',
        'GROOT BIJGAARDEN',
        'GRUPONT',
        'HAACHT',
        'HAALTERT',
        'HABAY',
        'HAININ',
        'HAL',
        'HALLE',
        'HAM SUR HEURE',
        'HAM SUR SAMBRE',
        'HAMBOS',
        'HAMOIR',
        'HANSBEKE',
        'HARCHIES',
        'HARELBEKE',
        'HAREN',
        'HAREN SUD',
        'HAREN ZUID',
        'HASSELT',
        'HAUTE FLONE',
        'HAVERSIN',
        'HAVRE',
        'HEIDE',
        'HEIST',
        'HEIST OP DEN BERG',
        'HEIZIJDE',
        'HEMIKSEM',
        'HENNUYERES',
        'HERENT',
        'HERENTALS',
        'HERNE',
        'HERSEAUX',
        'HERSTAL',
        'HERZELE',
        'HEUSDEN',
        'HEVER',
        'HEVERLEE',
        'HILLEGEM',
        'HOBOKEN POLDER',
        'HOEI',
        'HOEILAART',
        'HOFSTADE',
        'HOLLEKEN',
        'HONY',
        'HOURAING',
        'HOURPES',
        'HOUYET',
        'HOVE',
        'HUIZINGEN',
        'HUY',
        'IDDERGEM',
        'IDEGEM',
        'IEPER',
        'INGELMUNSTER',
        'IZEGEM',
        'JAMBES',
        'JAMBES EST',
        'JAMIOULX',
        'JEMAPPES',
        'JEMELLE',
        'JEMEPPE SUR MEUSE',
        'JEMEPPE SUR SAMBRE',
        'JETTE',
        'JURBISE',
        'JUSLENVILLE',
        'KALMTHOUT',
        'KAPELLE OP DEN BOS',
        'KAPELLEN',
        'KESSEL',
        'KIEWIT',
        'KIJKUIT',
        'KNOKKE',
        'KOKSIJDE',
        'KOMEN',
        'KONTICH',
        'KORTEMARK',
        'KORTENBERG',
        'KORTRIJK',
        'KWATRECHT',
        'LA HULPE',
        'LA LOUVIERE CENTRE',
        'LA LOUVIERE SUD',
        'LA ROCHE',
        'LABUISSIERE',
        'LANDEGEM',
        'LANDELIES',
        'LANDEN',
        'LANDSKOUTER',
        'LANGDORP',
        'LE CAMPINAIRE',
        'LEBBEKE',
        'LEDE',
        'LEIGNON',
        'LEMAN',
        'LEMBEEK',
        'LENS',
        'LEOPOLDSBURG',
        'LESSINES',
        'LEUVEN',
        'LEUZE',
        'LEVAL',
        'LIBRAMONT',
        'LICHTERVELDE',
        'LIEDEKERKE',
        'LIEGE GUILLEMINS',
        'LIEGE JONFOSSE',
        'LIEGE PALAIS',
        'LIER',
        'LIERDE',
        'LIERS',
        'LIGNY',
        'LILLOIS',
        'LIMAL',
        'LINKEBEEK',
        'LISSEWEGE',
        'LOBBES',
        'LODELINSART',
        'LOKEREN',
        'LOMMEL',
        'LONDERZEEL',
        'LONZEE',
        'LOT',
        'LOUVAIN LA NEUVE UNIV',
        'LUSTIN',
        'LUTTRE',
        'MAFFLE',
        'MALDEREN',
        'MANAGE',
        'MARBEHAN',
        'MARCHE EN FAMENNE',
        'MARCHE LES DAMES',
        'MARCHE LEZ ECAUSSINNES',
        'MARCHIENNE AU PONT',
        'MARCHIENNE ZONE',
        'MARIA AALTER',
        'MARIEMBOURG',
        'MARLOIE',
        'MASNUY SAINT PIERRE',
        'MAUBRAY',
        'MAZY',
        'MECHELEN',
        'MECHELEN NEKKERSPOEL',
        'MEISER',
        'MELKOUWEN',
        'MELLE',
        'MELREUX HOTTON',
        'MELSELE',
        'MENEN',
        'MERCHTEM',
        'MERELBEKE',
        'MERODE',
        'MERY',
        'MEVERGNIES ATTRE',
        'MILMORT',
        'MOENSBERG',
        'MOL',
        'MOLLEM',
        'MOMALLE',
        'MONS',
        'MONT SAINT GUIBERT',
        'MOORTSELE',
        'MORLANWELZ',
        'MORTSEL',
        'MORTSEL DEURNESTEENWEG',
        'MORTSEL OUDE GOD',
        'MOUSCRON',
        'MOUSTIER',
        'MUIZEN',
        'MUNKZWALM',
        'NAMECHE',
        'NAMUR',
        'NANINNE',
        'NATOYE',
        'NEERPELT',
        'NEERWINDEN',
        'NESSONVAUX',
        'NEUFCHATEAU',
        'NEUFVILLES',
        'NIEL',
        'NIEUWKERKEN WAAS',
        'NIJLEN',
        'NIJVEL',
        'NIMY',
        'NINOVE',
        'NIVELLES',
        'NOSSEGEM',
        'OBAIX BUZET',
        'OBOURG',
        'OKEGEM',
        'OLEN',
        'OOSTENDE',
        'OOSTKAMP',
        'OPWIJK',
        'OTTIGNIES',
        'OUD HEVERLEE',
        'OUDEGEM',
        'OUDENAARDE',
        'OVERPELT',
        'PALISEUL',
        'PAPIGNIES',
        'PECROT',
        'PEPINSTER',
        'PEPINSTER CITE',
        'PERUWELZ',
        'PHILIPPEVILLE',
        'PIETON',
        'POIX SAINT HUBERT',
        'PONT A CELLES',
        'PONT DE SERAING',
        'POPERINGE',
        'POULSEUR',
        'PROFONDSART',
        'PRY',
        'PUURS',
        'QUAREGNON',
        'QUEVY',
        'QUIEVRAIN',
        'REBAIX',
        'REMICOURT',
        'RHISNES',
        'RIVAGE',
        'RIXENSART',
        'ROESELARE',
        'RONET',
        'RONSE',
        'ROUX',
        'RUISBROEK',
        'SAUVEGARDE',
        'SAINT DENIS BOVESSE',
        'SAINT GHISLAIN',
        'SAINT JOB',
        'SART BERNARD',
        'SCHAARBEEK',
        'SCHAERBEEK',
        'SCHELDEWINDEKE',
        'SCHELLEBELLE',
        'SCHENDELBEKE',
        'SCHOONAARDE',
        'SCHULEN',
        'SCLAIGNEAUX',
        'SCLESSIN',
        'SERSKAMP',
        '\'S GRAVENBRAKEL',
        'SILLY',
        'S\'INAAI',
        'SINT AGATHA BERCHEM',
        'SINT DENIJS BOEKEL',
        'SINT GENESIUS RODE',
        'SINT GILLIS',
        'SINT JOB',
        'SINT JORIS WEERT',
        'SINT KATELIJNE WAVER',
        'SINT MARIABURG',
        'SINT MARTENS BODEGEM',
        'SINT NIKLAAS',
        'SINT TRUIDEN',
        'SLEIDINGE',
        'SOIGNIES',
        'SOLRE SUR SAMBRE',
        'SPA',
        'SPA-GERONSTERE',
        'STATTE',
        'STOCKEM',
        'SY',
        'TAMINES',
        'TEMSE',
        'TERHAGEN',
        'TERHULPEN',
        'TERNAT',
        'TESTELT',
        'THEUX',
        'THIEU',
        'THUIN',
        'THULIN',
        'TIELEN',
        'TIELT',
        'TIENEN',
        'TILFF',
        'TILLY',
        'TOLLEMBEEK',
        'TONGEREN',
        'TORHOUT',
        'TOURNAI',
        'TROIS PONTS',
        'TROOZ',
        'TUBIZE',
        'TURNHOUT',
        'UCCLE CALEVOET',
        'UCCLE STALLE',
        'UKKEL KALEVOET',
        'UKKEL STALLE',
        'VELTEM',
        'VERTRIJK',
        'VERVIERS CENTRAL',
        'VERVIERS PALAIS',
        'VEURNE',
        'VIANE MOERBEKE',
        'VICHTE',
        'VIELSALM',
        'VIJFHUIZEN',
        'VILLE POMMEROEUL',
        'VILLERS LA VILLE',
        'VILVOORDE',
        'VIRTON',
        'VISE',
        'VIVILLE',
        'VOROUX GOREUX',
        'VORST OOST',
        'VORST ZUID',
        'WAARSCHOOT',
        'WALCOURT',
        'WAREGEM',
        'WAREMME',
        'WATERLOO',
        'WATERMAAL',
        'WATERMAEL',
        'WAVER',
        'WAVRE',
        'WEERDE',
        'WELKENRAEDT',
        'WELLE',
        'WERVIK',
        'WESPELAAR TILDONK',
        'WETTEREN',
        'WEVELGEM',
        'WEZEMAAL',
        'WICHELEN',
        'WIJGMAAL',
        'WILDERT',
        'WILLEBROEK',
        'WONDELGEM',
        'YVES GOMEZEE',
        'YVOIR',
        'ZANDBERGEN',
        'ZAVENTEM',
        'ZEDELGEM',
        'ZEEBRUGGE DORP',
        'ZEEBRUGGE STRAND',
        'ZELE',
        'ZELLIK',
        'ZICHEM',
        'ZINGEM',
        'ZOTTEGEM',
        'ZWANKENDAMME',
        'ZWIJNDRECHT');

/*
 * This function will generate a javascript array called data
 */
function generate_js_array($stations) {
    echo "var data= new Array(";
    $nOfStations = count($stations);
    foreach($stations as $i => $value) {
        echo "\"" . $value . "\"";
        if($i < $nOfStations -1) {
            echo ",";
        }
    }
    echo ");";
}

/*
 * This function returns the timestamp - if downloaded once and timestamps match, no need to download it again
 */

function get_timestamp(){
    return "070810";
}
?>
